### ISSUE TITLE
Loaded mesh shifted

### ISSUE THREAD

**Issue by kgv** [Game4all/bevy_vox_mesh#4]
Light gray voxel is loaded from ".vox" file with `Transform::from_translation(Vec3::ZERO)`. But in fact it located at `(1,1,1)`
![Untitled](https://user-images.githubusercontent.com/863800/182835224-1d3f0fb0-931f-487d-8ff1-11e1a1b5b548.png)

**Comment by Game4all** [comment]
This stems from the meshing which requires the voxel data to be padded by 1 on each direction, resulting in the observed offset. This just needs a processing step post-voxel meshing to fix the offset issue.

**Comment by kgv** [comment]
Since this is a known specificity of the internal implementation, then we can close the Issue. I thought that this might be a bug in the implementation

**Comment by Game4all** [comment]
I'll leave this open as a remainder to fix this.

**Comment by kgv** [comment]
If I understand correctly, it's dependent issue: https://github.com/bonsairobo/block-mesh-rs/issues/6 ?

**Comment by Game4all** [comment]
yes altough that can be fixed by applying a post-processing step on the generated vertices to remove the offset.

**Comment by Game4all** [comment]
@kgv Just pushed c152b3cf5923b9fae50e0c8d97abde9cf8ea5d39 on master which should fix the aforementionned issue.
